on: [push, pull_request]

name: CFAST

jobs:
  build-rpm:
    name: Build RPM
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - "fedora:36"
          - "rockylinux:9"
          - "rockylinux:8"
        cfast-version:
          - "7.0.1"
          - "7.1.0"
          - "7.1.1"
          - "7.1.2"
          - "7.2.0"
          - "7.2.1"
          - "7.2.2"
          - "7.2.3"
          - "7.2.4"
          - "7.3.0"
          - "7.3.1"
          - "7.4.0"
          - "7.4.2"
          - "7.4.3"
          - "7.5.1"
          - "7.5.2"
          - "7.7.0"
          - "7.7.1"
          - "7.7.2"
          - "7.7.3"
          # - "latest"
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v3
      - name: Install prerequisites
        run: dnf install -y git gcc-gfortran rpmdevtools make
      - name: Build RPM
        run: |
          cd cfast
          export version=${{ matrix.cfast-version }}
          export commit=$(awk -F, -v version="$version" '$1 == version { print $2; exit }' versions.csv)
          export date=$(awk -F, -v version="$version" '$1 == version { print $3; exit }' versions.csv)
          export version_patch=$(awk -F, -v version="$version" '$1 == version { print $4; exit }' versions.csv)
          ./buildrpm.sh $version $commit $date $version_patch
      - uses: actions/upload-artifact@v3
        with:
          name: CFAST-RPMs
          path: |
            dist/*.rpm
