on: [push, pull_request]

name: Continuous integration

jobs:
  build-rpm:
    name: Build RPM
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["fedora:35","centos:8.4.2105"]
        fds-version:
          - "5.5.3"
          - "6.1.2"
          - "6.2.0"
          - "6.3.0"
          - "6.3.1"
          - "6.3.2"
          - "6.4.0"
          - "6.5.0"
          - "6.5.1"
          - "6.5.2"
          - "6.5.3"
          - "6.6.0"
          - "6.7.0"
          - "6.7.1"
          - "6.7.3"
          - "6.7.4"
          - "6.7.5"
          - "6.7.6"
          - "6.7.7"
          - "latest"
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - name: Add intel RPM repo
        run: |
          tee > /tmp/oneAPI.repo << EOF
          [oneAPI]
          name=Intel® oneAPI repository
          baseurl=https://yum.repos.intel.com/oneapi
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          EOF
          mv /tmp/oneAPI.repo /etc/yum.repos.d
      - name: Install prerequisites
        run: yum install -y git gcc procps kmod openssl-devel cargo rpmdevtools make
      - run: yum install -y intel-basekit intel-hpckit
      - name: Build RPM
        run: |
          cd ${{ matrix.fds-version }}
          mkdir -p rpmbuild/SOURCES
          cp backports.patch rpmbuild/SOURCES || true
          bash ../makerpm.sh
      - uses: actions/upload-artifact@v2
        with:
          name: FDS-RPMs
          path: |
            ${{ matrix.fds-version }}/rpmbuild/RPMS/*/*.rpm
  build-arch:
    name: Build Arch Linux package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["archlinux:base-devel"]
        fds-version:
          - "5.5.3"
          - "6.1.2"
          - "6.2.0"
          - "6.3.0"
          - "6.3.1"
          - "6.3.2"
          - "6.4.0"
          - "6.5.0"
          - "6.5.1"
          - "6.5.2"
          - "6.5.3"
          - "6.6.0"
          - "6.7.0"
          - "6.7.1"
          - "6.7.3"
          - "6.7.4"
          - "6.7.5"
          - "6.7.6"
          - "6.7.7"
          - "latest"
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: pacman -Sy --noconfirm wget
      - run: ./install-oneapi.sh
      - name: Build Package
        run: |
          useradd builder
          cd ${{ matrix.fds-version }}
          chown -R builder:builder .
          su builder
          makepkg -f
      - uses: actions/upload-artifact@v2
        with:
          name: FDS-Arch
          path: |
            ${{ matrix.fds-version }}/*.zst
