on: [push, pull_request]

name: Continuous integration

jobs:
  build-rpm:
    name: Build RPM
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - "fedora:36"
          - "rockylinux:9"
          # - "rockylinux:8"
        fds-version:
          # - "5.5.3"
          # - "6.1.2"
          # - "6.2.0"
          # - "6.3.0"
          # - "6.3.1"
          # - "6.3.2"
          # - "6.4.0"
          # - "6.5.0"
          # - "6.5.1"
          # - "6.5.2"
          # - "6.5.3"
          # - "6.6.0"
          # - "6.7.0"
          # - "6.7.1"
          # - "6.7.3"
          # - "6.7.4"
          # - "6.7.5"
          # - "6.7.6"
          # - "6.7.7"
          # - "6.7.8"
          - "6.7.9"
          - "latest"
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v3
      - name: Add intel RPM repo
        run: |
          tee > /tmp/oneAPI.repo << EOF
          [oneAPI]
          name=Intel® oneAPI repository
          baseurl=https://yum.repos.intel.com/oneapi
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          EOF
          mv /tmp/oneAPI.repo /etc/yum.repos.d
      - name: Install prerequisites
        run: dnf install -y git gcc kmod openssl-devel cargo rpmdevtools make
      - name: Install fedora libxcrypt-compat
        run: dnf install -y libxcrypt-compat || true
      - name: Install fedora procps
        run: dnf install -y procps || true
      - run: dnf install -y intel-oneapi-mpi-devel intel-oneapi-mkl-devel intel-oneapi-compiler-fortran openmpi-devel
      - run: /opt/intel/oneapi/modulefiles-setup.sh
      - name: Build RPM
        run: |
          cd ${{ matrix.fds-version }}
          bash ../makerpm.sh
      - uses: actions/upload-artifact@v3
        with:
          name: FDS-RPMs
          path: |
            ${{ matrix.fds-version }}/rpmbuild/RPMS/*/*.rpm
  build-deb:
    name: Build deb
    if: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fds-version:
          - "5.5.3"
          - "6.1.2"
          - "6.2.0"
          - "6.3.0"
          - "6.3.1"
          - "6.3.2"
          - "6.4.0"
          - "6.5.0"
          - "6.5.1"
          - "6.5.2"
          - "6.5.3"
          - "6.6.0"
          - "6.7.0"
          - "6.7.1"
          - "6.7.3"
          - "6.7.4"
          - "6.7.5"
          - "6.7.6"
          - "6.7.7"
          - "6.7.8"
          - "6.7.9"
          - "latest"
    steps:
      - uses: actions/checkout@v3
      - name: Add intel apt repo
        run: |
          wget -qO- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | sudo tee /etc/apt/trusted.gpg.d/intel-oneapi.asc
          sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
          sudo apt-get update
      - name: Install prerequisites
        run: sudo apt-get install -y git gcc openssl make devscripts debhelper
      - run: sudo apt-get install -y intel-oneapi-mpi intel-oneapi-mkl intel-oneapi-compiler-fortran
      - name: Build deb
        run: |
          cd ${{ matrix.fds-version }}/deb
          bash build_debian.sh
      - uses: actions/upload-artifact@v3
        with:
          name: FDS-DEBs
          path: |
            ${{ matrix.fds-version }}/deb/*.deb
  build-arch:
    name: Build Arch Linux package
    if: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["archlinux:base-devel"]
        fds-version:
          # - "5.5.3"
          - "6.1.2"
          - "6.2.0"
          - "6.3.0"
          - "6.3.1"
          - "6.3.2"
          - "6.4.0"
          - "6.5.0"
          - "6.5.1"
          - "6.5.2"
          - "6.5.3"
          - "6.6.0"
          - "6.7.0"
          - "6.7.1"
          - "6.7.3"
          - "6.7.4"
          - "6.7.5"
          - "6.7.6"
          - "6.7.7"
          - "6.7.8"
          - "6.7.9"
          - "latest"
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v3
      - name: Install prerequisites
        run: pacman -Sy --noconfirm wget git
      - run: ./install-oneapi.sh
      - name: Build Package
        run: |
          useradd builder
          cd ${{ matrix.fds-version }}
          chown -R builder:builder .
          cp ../fds.sh .
          su builder -c "makepkg -f"
      - uses: actions/upload-artifact@v3
        with:
          name: FDS-Arch
          path: |
            ${{ matrix.fds-version }}/*.zst
