on: [push, pull_request]

name: SMV

jobs:
  build-rpm:
    name: Build RPM
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - "fedora:36"
          - "fedora:37"
          - "fedora:38"
         # - "rockylinux:8"
         # - "rockylinux:9"
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v3
      - name: General update
        run: dnf update -y --refresh
      - name: Install prerequisites
        run: dnf install -y git gcc g++ rpmdevtools make
      - run: dnf install -y cmake gd-devel freeglut-devel glui-devel bash lua-filesystem lua gd freeglut glui libXmu-devel
      - name: Build RPM
        run: |
          cd smv
          bash ./buildrpm.sh
      - uses: actions/upload-artifact@v3
        with:
          name: FDS-RPMs
          path: |
            dist/*.rpm
